from PyQt4 import QtCore, QtGui

class Ui_Calcluator(object):
    def setupUi(self, Calcluator):
        Calcluator.setObjectName("Calcluator")
        Calcluator.resize(378, 304)
        Calcluator.setTabShape(QtGui.QTabWidget.Rounded)
        self.central_widget = QtGui.QWidget(Calcluator)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtGui.QGridLayout(self.central_widget)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.output_area = QtGui.QLineEdit(self.central_widget)
        self.output_area.setEnabled(True)


        self.output_area.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_area.setReadOnly(True)
        self.output_area.setObjectName("output_area")
        self.gridLayout.addWidget(self.output_area, 0, 0, 1, 4)
        self.button_cls = QtGui.QPushButton(self.central_widget)
        self.button_cls.setObjectName("button_cls")
        self.gridLayout.addWidget(self.button_cls, 1, 0, 1, 1)
        self.button_bck = QtGui.QPushButton(self.central_widget)
        self.button_bck.setObjectName("button_bck")
        self.gridLayout.addWidget(self.button_bck, 1, 1, 1, 1)
        self.button_close = QtGui.QPushButton(self.central_widget)
        self.button_close.setObjectName("button_close")
        self.gridLayout.addWidget(self.button_close, 1, 3, 1, 1)
        self.button_7 = QtGui.QPushButton(self.central_widget)
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 2, 0, 1, 1)
        self.button_8 = QtGui.QPushButton(self.central_widget)
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 2, 1, 1, 1)
        self.button_9 = QtGui.QPushButton(self.central_widget)
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 2, 2, 1, 1)
        self.button_div = QtGui.QPushButton(self.central_widget)
        self.button_div.setObjectName("button_div")
        self.gridLayout.addWidget(self.button_div, 2, 3, 1, 1)
        self.button_4 = QtGui.QPushButton(self.central_widget)
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 3, 0, 1, 1)
        self.button_5 = QtGui.QPushButton(self.central_widget)
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 3, 1, 1, 1)
        self.button_6 = QtGui.QPushButton(self.central_widget)
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 3, 2, 1, 1)
        self.button_mul = QtGui.QPushButton(self.central_widget)
        self.button_mul.setObjectName("button_mul")
        self.gridLayout.addWidget(self.button_mul, 3, 3, 1, 1)
        self.button_1 = QtGui.QPushButton(self.central_widget)
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 4, 0, 1, 1)
        self.button_2 = QtGui.QPushButton(self.central_widget)
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 4, 1, 1, 1)
        self.button_3 = QtGui.QPushButton(self.central_widget)
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 4, 2, 1, 1)
        self.button_sub = QtGui.QPushButton(self.central_widget)
        self.button_sub.setObjectName("button_sub")
        self.gridLayout.addWidget(self.button_sub, 4, 3, 1, 1)
        self.button_0 = QtGui.QPushButton(self.central_widget)
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 5, 0, 1, 1)
        self.button_dot = QtGui.QPushButton(self.central_widget)
        self.button_dot.setObjectName("button_dot")
        self.gridLayout.addWidget(self.button_dot, 5, 1, 1, 1)
        self.button_eval = QtGui.QPushButton(self.central_widget)
        self.button_eval.setObjectName("button_eval")
        self.gridLayout.addWidget(self.button_eval, 5, 2, 1, 1)
        self.button_add = QtGui.QPushButton(self.central_widget)
        self.button_add.setObjectName("button_add")
        self.gridLayout.addWidget(self.button_add, 5, 3, 1, 1)
        Calcluator.setCentralWidget(self.central_widget)
        self.menubar = QtGui.QMenuBar(Calcluator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 24))
        self.menubar.setObjectName("menubar")
        self.menu_calc = QtGui.QMenu(self.menubar)
        self.menu_calc.setObjectName("menu_calc")
        self.menu_mode = QtGui.QMenu(self.menubar)
        self.menu_mode.setObjectName("menu_mode")
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        Calcluator.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(Calcluator)
        self.toolBar.setObjectName("toolBar")
        Calcluator.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(Calcluator)
        self.statusBar.setObjectName("statusBar")
        Calcluator.setStatusBar(self.statusBar)
        self.action_copy = QtGui.QAction(Calcluator)
        icon = QtGui.QIcon()
        self.action_copy.setIcon(icon)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtGui.QAction(Calcluator)
        icon1 = QtGui.QIcon()
        self.action_paste.setIcon(icon1)
        self.action_paste.setObjectName("action_paste")
        self.action_undo = QtGui.QAction(Calcluator)
        icon2 = QtGui.QIcon()
        self.action_undo.setIcon(icon2)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtGui.QAction(Calcluator)
        icon3 = QtGui.QIcon()
        self.action_redo.setIcon(icon3)
        self.action_redo.setObjectName("action_redo")
        self.action_quit = QtGui.QAction(Calcluator)
        icon4 = QtGui.QIcon()
        self.action_quit.setIcon(icon4)
        self.action_quit.setObjectName("action_quit")
        self.action_setting = QtGui.QAction(Calcluator)
        icon5 = QtGui.QIcon()
        
        self.action_setting.setIcon(icon5)
        self.action_setting.setObjectName("action_setting")
        self.action_help = QtGui.QAction(Calcluator)
        self.action_help.setObjectName("action_help")
        self.action_about = QtGui.QAction(Calcluator)
        self.action_about.setObjectName("action_about")
        self.action_base_mode = QtGui.QAction(Calcluator)
        self.action_base_mode.setObjectName("action_base_mode")
 

        self.retranslateUi(Calcluator)
        QtCore.QObject.connect(self.action_quit, QtCore.SIGNAL("triggered()"), Calcluator.close)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL("clicked()"), Calcluator.close)
        QtCore.QMetaObject.connectSlotsByName(Calcluator)

    def retranslateUi(self, Calcluator):
        Calcluator.setWindowTitle(QtGui.QApplication.translate("Calcluator", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.output_area.setText(QtGui.QApplication.translate("Calcluator", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cls.setText(QtGui.QApplication.translate("Calcluator", "CLS", None, QtGui.QApplication.UnicodeUTF8))
        self.button_bck.setText(QtGui.QApplication.translate("Calcluator", "BCK", None, QtGui.QApplication.UnicodeUTF8))
        self.button_close.setText(QtGui.QApplication.translate("Calcluator", "CLOSE", None, QtGui.QApplication.UnicodeUTF8))
        self.button_7.setText(QtGui.QApplication.translate("Calcluator", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.button_8.setText(QtGui.QApplication.translate("Calcluator", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.button_9.setText(QtGui.QApplication.translate("Calcluator", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.button_div.setText(QtGui.QApplication.translate("Calcluator", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.button_4.setText(QtGui.QApplication.translate("Calcluator", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.button_5.setText(QtGui.QApplication.translate("Calcluator", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.button_6.setText(QtGui.QApplication.translate("Calcluator", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mul.setText(QtGui.QApplication.translate("Calcluator", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.button_1.setText(QtGui.QApplication.translate("Calcluator", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.button_2.setText(QtGui.QApplication.translate("Calcluator", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3.setText(QtGui.QApplication.translate("Calcluator", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.button_sub.setText(QtGui.QApplication.translate("Calcluator", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_0.setText(QtGui.QApplication.translate("Calcluator", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_dot.setText(QtGui.QApplication.translate("Calcluator", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.button_eval.setText(QtGui.QApplication.translate("Calcluator", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setText(QtGui.QApplication.translate("Calcluator", "+", None, QtGui.QApplication.UnicodeUTF8))
        

